server:
  port: 8091
spring:
  application:
    name: demo-consumer
#eureka配置
eureka:
  client:
    service-url:
 #     defaultZone: http://localhost8080/eureka,http://localhost8081/eureka,http://localhost8082/eureka #集群配置
       defaultZone: http://localhost:8084/eureka
  instance:
    prefer-ip-address: true #注册ip到eureka
#feign的配置
feign:
  hystrix:
    enabled: true #feign打开hystrix
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full #日志级别
